language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'create database tests;'
  - mkdir -p ./tests/core/concrete5
  - git clone https://github.com/concrete5/concrete5.git ./tests/core/concrete5
  - cp -a ./tests/install ./tests/core/concrete5/web/config/
  - cp -a ./src/data ./tests/core/concrete5/web/packages/
  - ./tests/core/concrete5/cli/install-concrete5.php --config="./tests/test_config_travis.php"
  - mkdir ./tests/fixtures
  - mysqldump --xml -t -u travis tests > ./tests/fixtures/database.xml
  - mysqldump -u travis tests > ./tests/fixtures/database.sql
  - mysqldump -d -u travis tests > ./fixtures/schema.sql
  - cd tests
  - ./split_fixtures.php
